### ISSUE TITLE
Cannot set app setting - check door/window sensor

### ISSUE THREAD

**Issue by yhaugom** [daneedk/com.uc.heimdall#62] opened 2022-08-31 09:39 UTC
Not able to change the setting for pre enable check for door/window sensors on iOS.
In Norwegian the setting is labeled: "Sjekk dør/vindussensor(er)" under setting category "Kontroll før tilkobling".

Other settings works fine.

**Comment by daneedk** [comment] 2022-09-01 09:05
Hi Yhaugom,

I can't reproduce and haven't seen any earlier report on the switch not working. That settings is also no depending on any other setting so it not working is a bit strange.

Can you please use a browser (on a computer) and open https://tools.developer.homey.app/tools/app-settings
Next open Heimdall and select the settings tab.
Now open the javascript console in your browser (In Edge it's Extra/Developer/JavaScript-Console, in Safari its Developer/Show JavaScript Console) and ignore the information that's already shown.

No try to toggle the "Sjekk dør/vindussensor(er)" setting. There should be no new information in the console, the action should happen silently. If the console does show an error, please copy-paste it here.

**Comment by yhaugom** [comment] 2022-09-01 12:58
![image](https://user-images.githubusercontent.com/1016457/187919361-3e3f29c1-9cb7-42c9-859a-2e298d4305ee.png)

**Comment by yhaugom** [comment] 2022-09-01 12:59
Yes, will do. Also got an error in the app. See image.

**Comment by yhaugom** [comment] 2022-09-01 13:41
> Hi Yhaugom,
> 
> I can't reproduce and haven't seen any earlier report on the switch not working. That settings is also no depending on any other setting so it not working is a bit strange.
> 
> Can you please use a browser (on a computer) and open https://tools.developer.homey.app/tools/app-settings Next open Heimdall and select the settings tab. Now open the javascript console in your browser (In Edge it's Extra/Developer/JavaScript-Console, in Safari its Developer/Show JavaScript Console) and ignore the information that's already shown.
> 
> No try to toggle the "Sjekk dør/vindussensor(er)" setting. There should be no new information in the console, the action should happen silently. If the console does show an error, please copy-paste it here.

Tried this, and there is no output to the console when trying to toggle the setting. Toggle does not work in browser either.

**Comment by daneedk** [comment] 2022-09-01 14:42
Ok, seeing you have an error I am interested what’s in the console when opening the settingspages. Can you open the console before going into Heimdalls settings and copy paste the output here?

**Comment by yhaugom** [comment] 2022-09-01 20:39
What part are you interested in? I am not willing to post everything here for everyone to see, and it is a lot to expand and go through.
![image](https://user-images.githubusercontent.com/1016457/188007985-eca6dccd-cea3-443b-a093-79de4748c00f.png)

**Comment by daneedk** [comment] 2022-09-02 08:20
Well, I would have expected (or hoped) to see an error in the log, what you show here is clear enough, no need to see more of this as this is what is shown when everything is ok.

Do you always get the getZonesError?

What I now see from the image you posted, the slider for the "Sjekk dør/vindussensor(er)" setting is misshaped. It should be round but looks to be an ellips. That's very weird, al sliders are made of the same CSS component. 

I'm a bit lost here what is wrong. Somehow the rendering of the webpage fails but it doesn't throw an error. 
- What browser did you try this on on your computer?
- Is it possible to try a different browser on your computer?
- Would you be willing to temporary change Homey's language to English?

**Comment by yhaugom** [comment] 2022-09-02 14:39
I only got the error once actually. I cannot re-produce it anymore. So maybe that was just "a glitch".

The miss-shaping only occurs when I try to toggle it. It seems to be starting the toggle animation, but is then sometimes stuck after a very short time. 
I have tried all the other toggles on the same settings page, and all of them is working properly.

I have testet it in Google Chrome and Microsoft Edge. Both the same.

I also tested switching to English language with same result.

**Comment by daneedk** [comment] 2022-09-02 15:36
Ah, ok, if it happend only once it's not related to the slider, most likely just a glitch.

Are you capable of running the app from the CLI? I see something in the code that isn't correct but if this causes the problems you're experiencing I would have expected every user to have this problem.

(How to install an app from the CLI is explained here: https://community.homey.app/t/how-to-cli-install-method/198)

**Comment by yhaugom** [comment] 2022-09-02 15:38
Yes, I should be able to do that.

**Comment by daneedk** [comment] 2022-09-02 15:42
Ah, great!

The thing I found is a double id value on the input that defines the slider.

Line 273 In the file /settings/index.html reads:
` <input id="checkContactAtArming" id="checkContactAtArming" type="checkbox" onclick="saveSettings()">`
but should be:
` <input id="checkContactAtArming" type="checkbox" onclick="saveSettings()">`

Could you edit that line in the code, run the app and see if that fixes the problem you're experiencing?

Thanks!

**Comment by yhaugom** [comment] 2022-09-02 16:59
Did not help unfortunately...
![image](https://user-images.githubusercontent.com/1016457/188202845-d7050794-a496-476d-b8dc-5cb89ba8526a.png)

**Comment by yhaugom** [comment] 2022-09-02 17:27
Oh, I found the reason.
On line 812 in saveSettings.js you do this: 
`if ( heimdallSettings.spokenDoorOpenAtArming ) {
        document.getElementById('checkContactAtArming').checked = true
        heimdallSettings.checkContactAtArming = true
    }`

That means that if I have the setting spokenDoorOpenAtArming set to true (which I have), then the setting 'checkContactAtArmin' is immediately set back to true.

**Comment by daneedk** [comment] 2022-09-02 17:35
Ah, Yeah, I knew I had some settings that depend on other settings, but I wrote that code so long ago I didn't remember which setting blocked which. I looked into that earlier, mentioned it in my first reply but was clearly wrong.

Guess I'll have to better document my code ;)

Glad it's clear now, as it is intended behaviour I'm gonna close this issue.

**Closed by daneedk** 2022-09-02 17:35 UTC
