### ISSUE TITLE
Homey Speaks

### ISSUE THREAD

**Issue by jfmulder** [daneedk/com.uc.heimdall#42] opened 2019-10-17 20:41 UTC
Since last update Homey says when alarm is switched off while all speaking settings are switched off

**Comment by daneedk** [comment] 2019-10-18 08:25
Hello @jfmulder 

I can't reproduce what you are experiencing and ***Heimdall*** should only send out speech when it's enabled, can you provide me with some more information?

- What you you mean 'when the alarm is switched off'? Has the **Alarm State** been _activated_ and you want to _deactivate_ it or do you mean setting the **Surveillance Mode** to _Disarmed_?
- What text is the *exact* text that is spoken out?
- Did you try enabling and disabling the setting for the particular action?

**Comment by jfmulder** [comment] 2019-10-18 10:09
Hi Danee,

I made a button that sets the alarm to Disarmed and it switches alarm state to deactivate as well (two in one function).

It says that the alarm has been switched off (in Dutch).

Yes, I tried to enable and disable, but I did not try the results yet.

When I arive at home Homey gives a welcome message, the alarm has been switched off message started to talk trough the welcome.

I'll keep you posted. It was just to inform you. Further on I'm a happy user ;)

Greets,

Alfred

Outlook voor Android downloaden<https://aka.ms/ghei36>

________________________________

**Comment by daneedk** [comment] 2019-11-15 17:46
Hello @jfmulder,

Are you still experiencing this issue or can I close it?

Thanks

**Comment by jfmulder** [comment] 2019-12-01 11:22
Hoi,

Ik heb de indruk dat ik na een nieuwe versie (update) de schuifjes van de instellingen heen en weer moet zetten en dat dan het issue weg is. Het issue was terug gekomen, maar er was in de tussentijd ook weer een update geweest. Inmiddels is alles weer een tijdje stabiel.

Dank, uiteraard kun je ticket sluiten.

Gr.
Alfred


Outlook voor Android downloaden<https://aka.ms/ghei36>
________________________________

**Closed** 2019-12-05 19:49 UTC
